"""empty message

Revision ID: 5eb5f94764a5
Revises: 93f27311304c
Create Date: 2018-12-20 07:51:21.001160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb5f94764a5'
down_revision = '93f27311304c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('valueId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'valueId')
    # ### end Alembic commands ###
