"""empty message

Revision ID: 9e5416e759f3
Revises: eaf9e10012a7
Create Date: 2019-01-27 19:21:43.219313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5416e759f3'
down_revision = 'eaf9e10012a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('sampleId', sa.Integer(), nullable=False))
    op.drop_column('data', 'valueId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('valueId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('data', 'sampleId')
    # ### end Alembic commands ###
