"""empty message

Revision ID: ccc92655b4d6
Revises: 5eb5f94764a5
Create Date: 2019-01-27 14:09:47.653579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc92655b4d6'
down_revision = '5eb5f94764a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('valueId', sa.Integer(), nullable=True),
    sa.Column('accX', sa.Float(), nullable=True),
    sa.Column('accY', sa.Float(), nullable=True),
    sa.Column('accZ', sa.Float(), nullable=True),
    sa.Column('gyroX', sa.Float(), nullable=True),
    sa.Column('gyroY', sa.Float(), nullable=True),
    sa.Column('gyroZ', sa.Float(), nullable=True),
    sa.Column('magX', sa.Float(), nullable=True),
    sa.Column('magY', sa.Float(), nullable=True),
    sa.Column('magZ', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
