"""empty message

Revision ID: deebcddb82e5
Revises: 9e5416e759f3
Create Date: 2019-02-05 01:20:16.316442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'deebcddb82e5'
down_revision = '9e5416e759f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('accX', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('accY', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('accZ', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('gyroX', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('gyroY', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('gyroZ', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('magX', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('magY', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('magZ', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('sampleId', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'data', ['sampleId'])
    op.drop_column('data', 'accy')
    op.drop_column('data', 'accx')
    op.drop_column('data', 'magz')
    op.drop_column('data', 'gyrox')
    op.drop_column('data', 'gyroz')
    op.drop_column('data', 'magy')
    op.drop_column('data', 'magx')
    op.drop_column('data', 'accz')
    op.drop_column('data', 'gyroy')
    op.drop_column('data', 'sampleid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('sampleid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('data', sa.Column('gyroy', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('accz', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('magx', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('magy', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('gyroz', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('gyrox', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('magz', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('accx', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('accy', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'data', type_='unique')
    op.drop_column('data', 'sampleId')
    op.drop_column('data', 'magZ')
    op.drop_column('data', 'magY')
    op.drop_column('data', 'magX')
    op.drop_column('data', 'gyroZ')
    op.drop_column('data', 'gyroY')
    op.drop_column('data', 'gyroX')
    op.drop_column('data', 'accZ')
    op.drop_column('data', 'accY')
    op.drop_column('data', 'accX')
    # ### end Alembic commands ###
